In [1]:
import numpy as np

### `np.array`
- 행렬로 만들기 위해서 사용

In [2]:
x = np.array([10, 11, 12])

In [3]:
print(x)

[10 11 12]


In [4]:
y = np.array([[1, 2, 3], [11, 12, 13]])

In [5]:
print(y)

[[ 1  2  3]
 [11 12 13]]


### `np.arange`
- 순차적인 행렬을 만들기 위해서 사용

In [6]:
z = np.arange(10)

In [7]:
print(z)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
z = np.arange(1, 10)

In [9]:
print(z)

[1 2 3 4 5 6 7 8 9]


In [10]:
z = np.arange(1, 10, 2)

In [11]:
print(z)

[1 3 5 7 9]


In [12]:
z = np.arange(10, 101, 20)

In [13]:
print(z)

[10 30 50 70 90]


### `np.ones, np.zeros`

- np.ones: 1로 채운다

In [14]:
arr1 = np.ones((4, 5)) # 4 X 5 행렬

In [15]:
print(arr1)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
arr1 = np.ones((2, 3, 4)) # 3 X 4 행렬이 2개가 있다.

In [17]:
print(arr1)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [18]:
arr2 = np.zeros((2, 3))

In [19]:
print(arr2)

[[0. 0. 0.]
 [0. 0. 0.]]


- np.zeros: 0으로 채운다

In [20]:
arr2 = np.zeros((2, 3, 4)) # 3 X 4 행렬이 2개

In [21]:
print(arr2)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [22]:
arr2 = np.zeros((2, 3, 8, 8)) # (8 X 8 행렬이 3개) -> 2개

In [23]:
print(arr2)

[[[[0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0.]
   [

### `np.empty`

In [24]:
np.empty((3, 4)) # 초기화하고 싶을 때

array([[8.81370219e-312, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 1.59970521e-047, 4.27797136e-033,
        5.85106252e+170],
       [1.38293898e-047, 3.69597564e-057, 8.37526656e+169,
        9.39589280e+165]])

### `np.full`

In [25]:
np.full((3, 4, 3), 7) # 4 X 2 행렬을 3개 만들고 7로 채운다.

array([[[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]]])

### `np.eye`
- 단위 행렬을 만들기 위해서 사용

In [26]:
np.eye(4) # 단위 행렬을 만들기 위해서 사용

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### `np.linspace`
- 등차 수열을 만들기 위해서 사용

In [27]:
# 1부터 10까지 있는데 배열 개수를 3개로 만들고
# 등차 수열이 되도록한다.

np.linspace(1, 10, 3)

array([ 1. ,  5.5, 10. ])

In [28]:
# 1부터 10까지 있는데 배열 개수를 4개로 만들고
# 등차 수열이 되도록한다.

np.linspace(1, 10, 4)

array([ 1.,  4.,  7., 10.])

In [29]:
# 1부터 10까지 있는데 배열 개수를 6개로 만들고
# 등차 수열이 되도록한다.

np.linspace(1, 10, 6)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [30]:
# 1부터 100까지 있는데 배열 개수를 10개로 만들고
# 등차 수열이 되도록한다.

np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [31]:
# 1부터 128까지 있는데 배열 개수를 5개로 만들고
# 등차 수열이 되도록한다.

np.linspace(1, 128, 5)

array([  1.  ,  32.75,  64.5 ,  96.25, 128.  ])

### `np.reshape`
- 행렬을 다시 만들기 위해서 사용

In [32]:
x = np.arange(1, 16)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [33]:
x.shape

(15,)

In [34]:
x.reshape(3, 5) # 3 X 5의 행렬로 바꾸겠다.

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [35]:
x.reshape(5, 3, 1)

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [36]:
y = np.arange(16)

In [37]:
y.reshape(2, 8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [38]:
y.reshape(4, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [39]:
y.reshape(2, 2, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

### `np.random`

### `rand`
- 0-1 사이의 분포로 행렬을 생성

In [40]:
# 0과 1 사이의 분포로
# 2 X 3의 랜덤한 행렬 생성

np.random.rand(2, 3)

array([[0.68268395, 0.22439548, 0.31928794],
       [0.6622857 , 0.9386602 , 0.29905123]])

In [41]:
# 0과 1 사이에 분포로 
# 5 X 3의 랜덤한 행렬을 4개 생성

np.random.rand(4, 5, 3) 

array([[[0.72077894, 0.46010348, 0.56058512],
        [0.3885281 , 0.69017766, 0.70685324],
        [0.88043508, 0.3576232 , 0.67763435],
        [0.15598778, 0.98954457, 0.9859576 ],
        [0.36414308, 0.95193744, 0.77471757]],

       [[0.73438386, 0.05786919, 0.52968038],
        [0.58660828, 0.24154808, 0.06488665],
        [0.39157653, 0.88218108, 0.71102014],
        [0.11902787, 0.76850436, 0.2076667 ],
        [0.8266953 , 0.03886836, 0.30571121]],

       [[0.00834124, 0.86555257, 0.80694714],
        [0.07242109, 0.85103553, 0.83768072],
        [0.1401125 , 0.26711852, 0.24586239],
        [0.40949499, 0.9859395 , 0.66440975],
        [0.0905761 , 0.04260746, 0.0566202 ]],

       [[0.07729828, 0.05345157, 0.18285767],
        [0.19190505, 0.8353166 , 0.22682682],
        [0.70307094, 0.95268984, 0.65102118],
        [0.34952617, 0.52515414, 0.07383541],
        [0.35746337, 0.94582517, 0.4707523 ]]])

### `randn`
- <b>정규분포로 샘플링된 랜덤 데이터를 생성</b>

In [42]:
np.random.randn(3, 4)

array([[-1.20339368,  1.56850009, -2.37081368, -0.9817218 ],
       [-0.01644301, -1.12497602, -1.0247707 ,  0.72734096],
       [ 0.32926708,  0.39599246,  0.0309041 ,  0.48954942]])

In [43]:
np.random.randn(3, 2, 4)

array([[[ 2.08828675,  0.69386417,  0.77494967, -0.70356853],
        [-1.4025516 ,  0.25159108, -0.637497  , -2.23011767]],

       [[ 1.43767534,  1.1057967 , -0.57672895,  1.02649631],
        [-0.31860273,  1.08779445,  1.2446279 ,  1.52896998]],

       [[-1.37348465, -1.93482062,  1.10511707, -0.33935401],
        [ 0.66585698, -1.69083845,  0.02841856, -0.65484827]]])

### `randint`
- 특수 정수 사이에서 랜덤하게 샘플링

In [44]:
np.random.randint(1, 100, size=(3, 5))

array([[23, 44, 55, 45, 62],
       [62, 31, 24, 68, 43],
       [53, 83,  8, 20, 18]])

In [45]:
np.random.randint(1, 100, size=(3, 5, 2))

array([[[67, 85],
        [31, 45],
        [64, 49],
        [40, 92],
        [46, 18]],

       [[98, 60],
        [74, 62],
        [34, 70],
        [24, 96],
        [63, 59]],

       [[96, 13],
        [39, 56],
        [10, 15],
        [90, 84],
        [ 8, 19]]])

In [46]:
np.random.randint(1, 100, size=(5,))

array([77, 95, 77, 70, 75])

### `seed`
- 랜덤한 값을 동일하게 생성하고자 할때

In [47]:
np.random.seed(22)
np.random.randn(3, 4)

array([[-0.09194992, -1.46335065,  1.08179168, -0.23932517],
       [-0.49112914, -1.00227201,  0.9188215 , -1.1036321 ],
       [ 0.62649346, -0.56151378,  0.02885512, -0.23076719]])

### `choice`
- 주어진 배열로부터 랜덤 샘플링

In [48]:
np.random.choice(100, size=(3, 4))

array([[ 8, 40,  5, 27],
       [84, 34, 29, 82],
       [81, 38, 19, 19]])

In [49]:
x = np.array([1, 2, 3, 7.8, 5.6, 9.1])
np.random.choice(x, size=(2, 2))

array([[3. , 7.8],
       [7.8, 3. ]])

In [50]:
x = np.array([1, 2, 3, 7.8, 5.6, 9.1])
np.random.choice(x, size=(2, 2), replace=False) # 중복 제거

array([[5.6, 1. ],
       [9.1, 3. ]])

### `uniform, normal`
- 확률분포에 따른 데이터 생성

In [51]:
np.random.uniform(1.0, 3.0, size=(4, 5)) # 1-3 사이의 데이터 생성. 균일 분포

array([[2.40527104, 1.22379034, 2.84653985, 2.97777255, 2.35482155],
       [2.59032955, 1.0581527 , 1.35551814, 2.74985549, 2.48986415],
       [2.01618033, 1.2566678 , 1.96856848, 2.03154698, 1.62252933],
       [1.09132309, 1.87536132, 1.19176922, 1.09042022, 2.36965744]])

In [52]:
np.random.normal(size=(3, 4)) # 정규 분포

array([[-0.0788123 , -1.08516417,  0.59492845, -0.63890807],
       [-1.10783686,  2.10614576, -0.56738777, -0.47994979],
       [-1.92322986,  0.39958854, -1.04818387, -0.6938787 ]])