In [1]:
import numpy as np

### 1. 인덱싱

### 1차원 행렬

In [2]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
x[0]

0

In [4]:
x[-1]

9

In [5]:
x[len(x)-1]

9

In [6]:
x[3]

3

### 2차원 행렬

In [7]:
x = np.arange(10).reshape(2, 5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [8]:
x[0][0]

0

In [9]:
x[0][-1]

4

In [10]:
x[1][4]

9

In [11]:
x[1][-1]

9

In [12]:
x[1, 2]

7

In [13]:
x[0,2]

2

### 3차원 행렬

In [14]:
# 4 X 3 행렬이 3개가 있다.

x = np.arange(36).reshape(3, 4, 3) 
print(x)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [15]:
x[0][1][-1]

5

In [16]:
x[1, 2, 2]

20

In [17]:
x[2, 2, 1]

31

### 2. 슬라이싱

### 1차원 행렬

In [18]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [19]:
x[1:7]

array([1, 2, 3, 4, 5, 6])

In [20]:
x[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
x[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 2차원 행렬

In [22]:
x = np.arange(10).reshape(2, 5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [23]:
x[:, 1:4]

array([[1, 2, 3],
       [6, 7, 8]])

In [24]:
x[:, :2]

array([[0, 1],
       [5, 6]])

In [25]:
x[0, :2]

array([0, 1])

In [26]:
x[:1, :2]

array([[0, 1]])

### 3차원 행렬

In [27]:
x = np.arange(54).reshape(2, 9, 3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]]

 [[27 28 29]
  [30 31 32]
  [33 34 35]
  [36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]
  [48 49 50]
  [51 52 53]]]


In [28]:
x[:1, :2, :]

array([[[0, 1, 2],
        [3, 4, 5]]])

In [29]:
x[0, :2, :]

array([[0, 1, 2],
       [3, 4, 5]])

In [30]:
x[:, :3, 1:3]

array([[[ 1,  2],
        [ 4,  5],
        [ 7,  8]],

       [[28, 29],
        [31, 32],
        [34, 35]]])