In [1]:
import numpy as np

### `ravel, np.ravel`

- 다차원 배열을 1차원으로 변경
- `order` 파라미터
    - 'C' - row 우선 변경
    - 'F' - column 우선 변경

In [2]:
x = np.arange(15).reshape(3, 5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [3]:
tmp = x.ravel()

In [4]:
tmp[0] = 100

In [5]:
print(tmp)
print(x)

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14]
[[100   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]]


In [6]:
np.ravel(x)

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14])

In [7]:
x.ravel(order='C')

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14])

In [8]:
x.ravel(order='F')

array([100,   5,  10,   1,   6,  11,   2,   7,  12,   3,   8,  13,   4,
         9,  14])

### `flatten`
- 다차원 배열을 1차원으로 변경
- `ravel`과 차이점 : copy를 생성하여 변경한다.(즉 원본 데이터가 아닌 복사본을 반환)
- 'order' 파라미터
    - 'C' : row 우선 변경
    - 'F' : column 우선 변경

In [9]:
y = np.arange(15).reshape(3, 5)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [10]:
tmp2 = y.flatten()
tmp2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
tmp2[0] = 100

In [12]:
print(tmp2)
print(y)

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [13]:
y.flatten(order='C')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
y.flatten(order='F')

array([ 0,  5, 10,  1,  6, 11,  2,  7, 12,  3,  8, 13,  4,  9, 14])

In [15]:
x = np.arange(30).reshape(2, 3, 5)
print(x)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [16]:
x.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [17]:
x.ravel(order='C')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [18]:
x.ravel(order='F')

array([ 0, 15,  5, 20, 10, 25,  1, 16,  6, 21, 11, 26,  2, 17,  7, 22, 12,
       27,  3, 18,  8, 23, 13, 28,  4, 19,  9, 24, 14, 29])

### `reshape`
- array의 shape을 다른 차원으로 변경
- 주의할 점은 reshape한 후의 결과의 전체 원소 개수와 이전 개수가 같아야 가능하다.
- 이미지 데이터 벡터화 - 이미지는 기본적으로 2차원 혹은 3차원이나 트레이닝을 위해 1차원으로 변경하여 사용 된다.

In [19]:
x = np.arange(36)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]


In [20]:
print(x.shape)

(36,)


In [21]:
print(x.ndim)

1


In [22]:
x.reshape(6, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [23]:
x.reshape(6, -1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [24]:
x.reshape(9, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [25]:
x.reshape(-1, 12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [26]:
y = x.reshape(6, 6)

In [27]:
print(y.shape)
print(y.ndim)

(6, 6)
2


In [28]:
k = x.reshape(3, 3, -1)

In [29]:
print(k)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]


In [30]:
print(k.shape)
print(k.ndim)

(3, 3, 4)
3
