In [1]:
import numpy as np

In [2]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)

In [3]:
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [4]:
print(y)

[[0.08004878 0.49952427 0.95719272 0.30421188 0.03746489]
 [0.95239873 0.27482045 0.30771433 0.18530375 0.67820482]
 [0.21577679 0.27229329 0.66358926 0.68500376 0.70823914]]


### 연산 함수
- add, substract, multiply, divide

In [5]:
# 행렬의 덧셈

np.add(x, y) 

array([[ 0.08004878,  1.49952427,  2.95719272,  3.30421188,  4.03746489],
       [ 5.95239873,  6.27482045,  7.30771433,  8.18530375,  9.67820482],
       [10.21577679, 11.27229329, 12.66358926, 13.68500376, 14.70823914]])

In [6]:
# 행렬의 뺄셈

np.subtract(x, y) 

array([[-0.08004878,  0.50047573,  1.04280728,  2.69578812,  3.96253511],
       [ 4.04760127,  5.72517955,  6.69228567,  7.81469625,  8.32179518],
       [ 9.78422321, 10.72770671, 11.33641074, 12.31499624, 13.29176086]])

In [7]:
# 행렬의 곱셈

np.multiply(x, y)

array([[0.        , 0.49952427, 1.91438545, 0.91263565, 0.14985954],
       [4.76199363, 1.64892271, 2.1540003 , 1.48242997, 6.10384335],
       [2.15776786, 2.99522614, 7.96307113, 8.90504885, 9.91534792]])

In [8]:
# 행렬의 나눗셈

np.divide(x, y)

array([[  0.        ,   2.00190472,   2.08944338,   9.86154775,
        106.76664027],
       [  5.24990203,  21.83243632,  22.74837196,  43.17235991,
         13.27032745],
       [ 46.34418829,  40.39761746,  18.08347528,  18.97799808,
         19.76733459]])

In [9]:
# 행렬의 몫과 나머지

np.divmod(x, y)

(array([[  0.,   2.,   2.,   9., 106.],
        [  5.,  21.,  22.,  43.,  13.],
        [ 46.,  40.,  18.,  18.,  19.]]),
 array([[0.        , 0.00095146, 0.08561455, 0.26209306, 0.02872209],
        [0.23800637, 0.22877052, 0.23028478, 0.03193894, 0.18333738],
        [0.07426784, 0.10826856, 0.0553933 , 0.66993236, 0.54345639]]))

In [10]:
x + y

array([[ 0.08004878,  1.49952427,  2.95719272,  3.30421188,  4.03746489],
       [ 5.95239873,  6.27482045,  7.30771433,  8.18530375,  9.67820482],
       [10.21577679, 11.27229329, 12.66358926, 13.68500376, 14.70823914]])

In [11]:
x - y

array([[-0.08004878,  0.50047573,  1.04280728,  2.69578812,  3.96253511],
       [ 4.04760127,  5.72517955,  6.69228567,  7.81469625,  8.32179518],
       [ 9.78422321, 10.72770671, 11.33641074, 12.31499624, 13.29176086]])

In [12]:
x * y

array([[0.        , 0.49952427, 1.91438545, 0.91263565, 0.14985954],
       [4.76199363, 1.64892271, 2.1540003 , 1.48242997, 6.10384335],
       [2.15776786, 2.99522614, 7.96307113, 8.90504885, 9.91534792]])

In [13]:
x / y

array([[  0.        ,   2.00190472,   2.08944338,   9.86154775,
        106.76664027],
       [  5.24990203,  21.83243632,  22.74837196,  43.17235991,
         13.27032745],
       [ 46.34418829,  40.39761746,  18.08347528,  18.97799808,
         19.76733459]])

In [14]:
x // y

array([[  0.,   2.,   2.,   9., 106.],
       [  5.,  21.,  22.,  43.,  13.],
       [ 46.,  40.,  18.,  18.,  19.]])

In [15]:
x % y

array([[0.        , 0.00095146, 0.08561455, 0.26209306, 0.02872209],
       [0.23800637, 0.22877052, 0.23028478, 0.03193894, 0.18333738],
       [0.07426784, 0.10826856, 0.0553933 , 0.66993236, 0.54345639]])

### 통계 함수
- 평균, 분산, 중앙, 최대, 최소값 등등 통계 관련된 함수

In [16]:
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.08004878 0.49952427 0.95719272 0.30421188 0.03746489]
 [0.95239873 0.27482045 0.30771433 0.18530375 0.67820482]
 [0.21577679 0.27229329 0.66358926 0.68500376 0.70823914]]


In [17]:
np.mean(x)

7.0

In [18]:
np.mean(y)

0.45478578931009167

In [19]:
np.max(x)

14

In [20]:
np.max(y)

0.9571927232617863

In [21]:
# flatten한 상태에서 최댓값의 인덱스를 구한다.

np.argmax(x)

14

In [22]:
np.argmax(y)

2

In [23]:
# 분산     중앙값        표준편차
np.var(x), np.median(x), np.std(x)

(18.666666666666668, 7.0, 4.320493798938574)

In [24]:
np.var(y), np.median(y), np.std(y)

(0.08447404985090776, 0.3077143283456909, 0.29064419803413893)

### 집계 함수
- 합계, 누적합계 등을 계산

In [25]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [26]:
# 전체 합

np.sum(x)

105

In [27]:
# 누적 합계

np.cumsum(x)

array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105], dtype=int32)

In [28]:
# 행을 기준으로 합을 구한다.

np.sum(x, axis=0)

array([15, 18, 21, 24, 27])

In [29]:
# 열을 기준으로 합을 구한다.

np.sum(x, axis=1)

array([10, 35, 60])

### `any, all`
- `any` : 특정 조건을 만족하는 것이 하나라도 있으면 `True`, 아니면 `False`
- `all` : 모든 원소가 특정 조건을 만족하면, `True`, 아니면 `False`

In [30]:
z = np.random.randn(10)
print(z)

[-1.3486487  -0.94512177 -2.20406674 -0.33543138  0.69024245  0.97644389
 -0.90947683  2.02981678 -0.07497513 -0.33902645]


In [31]:
z > 0

array([False, False, False, False,  True,  True, False,  True, False,
       False])

In [32]:
np.any(z > 0) # 각각 원소에 대해서 0과 비교

True

In [33]:
np.all(z > 0)

False

### `where`
- 조건에 따라 선별적으로 값을 선택 가능
- 음수인 경우 0, 나머지는 그대로 값을 쓰는 경우

In [34]:
z = np.random.randn(10)

In [35]:
z

array([-0.31978303,  0.94575464, -1.24173276, -1.17676788,  0.83247756,
        0.02992686,  1.25976402, -1.02393062,  0.89450749, -1.59560752])

In [36]:
np.where(z>0, z, 0)

array([0.        , 0.94575464, 0.        , 0.        , 0.83247756,
       0.02992686, 1.25976402, 0.        , 0.89450749, 0.        ])