### 브로드캐스팅
- shape이 같은 두 ndarray에 대해서 연산은 각 원소별로 진행
- 연산되는 두 ndarray가 다른 shape을 갖는 경우 브로드캐스팅 후 진행

In [1]:
import numpy as np

- <b>shape이 같은 경우 연산</b>

In [2]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)

In [3]:
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [4]:
print(y)

[[0.35635878 0.39620425 0.44536462 0.46417001 0.01020208]
 [0.84968464 0.83248704 0.41816416 0.35987683 0.56645346]
 [0.54403743 0.81047946 0.68059871 0.47551933 0.58278667]]


In [5]:
x + y

array([[ 0.35635878,  1.39620425,  2.44536462,  3.46417001,  4.01020208],
       [ 5.84968464,  6.83248704,  7.41816416,  8.35987683,  9.56645346],
       [10.54403743, 11.81047946, 12.68059871, 13.47551933, 14.58278667]])

In [6]:
x * y

array([[0.        , 0.39620425, 0.89072924, 1.39251004, 0.04080833],
       [4.2484232 , 4.99492223, 2.9271491 , 2.87901462, 5.0980811 ],
       [5.4403743 , 8.91527402, 8.16718454, 6.18175129, 8.15901344]])

- <b>scalar와 연산</b>

In [7]:
x + 2

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [8]:
x * 2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [9]:
x ** 2

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]], dtype=int32)

In [10]:
x % 2 == 0

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

- <b>shape이 다른 경우</b>

In [11]:
a = np.arange(12).reshape(4, 3)
b = np.arange(100, 103)
c = np.arange(1000, 1004)
d = b.reshape(1, 3)
e = c.reshape(4, 1)

In [12]:
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [13]:
print(b)

[100 101 102]


In [14]:
print(c)

[1000 1001 1002 1003]


In [15]:
print(d)

[[100 101 102]]


In [16]:
print(e)

[[1000]
 [1001]
 [1002]
 [1003]]


In [17]:
a + b

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [18]:
a + d

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [19]:
a + e

array([[1000, 1001, 1002],
       [1004, 1005, 1006],
       [1008, 1009, 1010],
       [1012, 1013, 1014]])

In [20]:
x = np.arange(8).reshape(2, 4)
y = np.random.rand(16).reshape(2, 2, 4)

In [21]:
x

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [22]:
y

array([[[0.60906428, 0.6639115 , 0.48348323, 0.69472221],
        [0.28734227, 0.37156917, 0.48593929, 0.60235052]],

       [[0.14173696, 0.65107639, 0.87554456, 0.09432984],
        [0.58376503, 0.11271297, 0.20764288, 0.45252844]]])

In [23]:
x + y

array([[[0.60906428, 1.6639115 , 2.48348323, 3.69472221],
        [4.28734227, 5.37156917, 6.48593929, 7.60235052]],

       [[0.14173696, 1.65107639, 2.87554456, 3.09432984],
        [4.58376503, 5.11271297, 6.20764288, 7.45252844]]])