**Boolean indexing**
- ndarray 인덱싱 시, bool 리스트를 전달하여 True인 경우만 필터링
- 브로트캐스팅을 활용하여 ndarray로 부터 bool list 얻기

In [1]:
import numpy as np

In [13]:
x = np.random.randint(1, 100, size=10)
print(x)

[35 13 71 61 38 44 63 92 74 67]


In [14]:
even_mask = x % 2 == 0

In [15]:
print(even_mask)

[False False False False  True  True False  True  True False]


In [16]:
x[even_mask]

array([38, 44, 92, 74])

In [17]:
x[x % 2 == 0]

array([38, 44, 92, 74])

In [19]:
x[x > 30]

array([35, 71, 61, 38, 44, 63, 92, 74, 67])

**다중 조건 사용하기**
- and, or, not 키워드 사용 불가
- & : AND
- | : OR

In [21]:
# x % 2 == 0
# x < 30

x[(x % 2 == 0) & (x < 30)]

array([], dtype=int32)

In [22]:
# x < 30
# x > 50

x[(x < 30) | (x > 50)]

array([13, 71, 61, 63, 92, 74, 67])

**예제) 2019년 7월 서울 평균기온 데이터**
- 평균 기온이 25도를 넘는 날은?
- 평균 기온이 25도를 넘는 날의 평균 기온은?

In [23]:
temp = np.array(
        [23.9, 24.4, 24.1, 25.4, 27.6, 29.7,
         26.7, 25.1, 25.0, 22.7, 21.9, 23.6, 
         24.9, 25.9, 23.8, 24.7, 25.6, 26.9, 
         28.6, 28.0, 25.1, 26.7, 28.1, 26.5, 
         26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])

In [27]:
len(temp[temp > 25.0])

21

In [28]:
np.sum(temp > 25.0)

21

In [29]:
np.mean(temp[temp > 25.0])

26.857142857142858