In [1]:
import numpy as np

**np.linig.inv**
- 역행렬을 구할 때 사용
- 모든 차원의 값이 같아야 한다.

In [2]:
x = np.random.rand(3, 3)
print(x)

[[0.51087023 0.60164153 0.81749004]
 [0.64845086 0.07485418 0.31201335]
 [0.99647866 0.66012431 0.27881271]]


In [3]:
x @ np.linalg.inv(x)

array([[ 1.00000000e+00,  6.83236720e-17, -2.28364956e-16],
       [-5.03556250e-17,  1.00000000e+00, -3.50994313e-17],
       [-1.96345649e-17, -1.88813136e-16,  1.00000000e+00]])

In [4]:
np.matmul(x, np.linalg.inv(x))

array([[ 1.00000000e+00,  6.83236720e-17, -2.28364956e-16],
       [-5.03556250e-17,  1.00000000e+00, -3.50994313e-17],
       [-1.96345649e-17, -1.88813136e-16,  1.00000000e+00]])

**np.linalg.solve**
- $Ax = B$ 형태의 선형대수식 솔루션 제공

- 예제) 호랑이 홍합의 합 : 25, 호랑이 다리와 홍합 다리의 합 : 64
    - $x + y = 25$
    - $2x + 4y = 64$

$$\begin{pmatrix}
1 & 1 \\
2 & 4
\end{pmatrix}
\begin{pmatrix}
x \\
y
\end{pmatrix}
= \begin{pmatrix}
25 \\
64
\end{pmatrix}$$

In [5]:
A = np.array([[1, 1], [2, 4]])
B = np.array([25, 64])

x = np.linalg.solve(A, B)
print(x)

[18.  7.]


In [6]:
np.allclose(A@x, B)

True